<a href="https://colab.research.google.com/github/1264109842/cs59974_Assignment_4/blob/main/Assignment_4.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

In [1]:
# Imports and pip installations (if needed)
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier

# Part 1: Load the dataset

In [24]:
# Load the dataset (load remotely, not locally)

# Output the first 15 rows of the data
# Display a summary of the table information (number of datapoints, etc.)

# Load iris dataset
iris = load_iris()

# Display first 15 rows
first_15 = iris.data[:15]

# Display all classes of iris
className = list(iris.target_names)

# Display the name of each column
columnName = list(iris.feature_names)

# Number of datapoints
totalDatapoints = len(iris.data)

# Print the target name stored as label
# Species: 0 = setosa, 1 = versicolor, 2 = virginica
labels = list(iris.target)

print('First 15 rows: ' , first_15)
print('All class names: ', className)
print('Column names: ', columnName)
print('Total datapoints: ', totalDatapoints)
print('Target: ', labels)

First 15 rows:  [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]]
All class names:  ['setosa', 'versicolor', 'virginica']
Column names:  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Total datapoints:  150
Target:  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]


## About the dataset
Explain what the data is in your own words. What are your features and labels? What is the mapping of your labels to the actual classes?

Explanation:
    The dataset contains three classes of iris and their shapes. The features in iris dataset is speal length, speal width, petal length, and petal width. The labels of iris dataset is the number representation of each class that is setosa = 0, versicolor = 1, and virginica = 2. 

# Part 2: Split the dataset into train and test

In [25]:
# Take the dataset and split it into our features (X) and label (y)

# Features
X = iris.data

# Label
y = iris.target

# Use sklearn to split the features and labels into a training/test set. (90% train, 10% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.9, test_size=0.1, random_state=42)

# Convert training set and test set to a numpy array
X_train = np.array(X_train)
y_train = np.array(y_train)
X_test = np.array(X_test)
y_test = np.array(y_test)

# Part 3: Logistic Regression

In [26]:
# i. Use sklearn to train a LogisticRegression model on the training set

# Create a instance of logistic regression model
logisticReg = LogisticRegression()

# Train the model on training data
logisticReg.fit(X_train, y_train)


# ii. For a sample datapoint, predict the probabilities for each possible class

# Create a sample datapoint
sample = np.array([4.9, 2.1, 3.5, 1.1])

# Predict possible calss of sample datapoint
sample_predict = logisticReg.predict_proba(sample.reshape(1,-1))

# # Rounding to the nearest hundredth
sample_predict = np.round(sample_predict, 2)

print('Sample datapoint: ', sample)
print('The probability of setosa is: ' , sample_predict[:,0])
print('The probability of versicolor is: ' , sample_predict[:,1])
print('The probability of virginica is: ' , sample_predict[:,2])


# iii. Report on the score for Logistic regression model, what does the score measure?

#################################
# the score 

# Get the mean accuracy of logistic regression model
score = logisticReg.score(X_test, y_test)*100

# Print the score
print('\nThe score of test data: %.f%%\n' % score)

# iv. Extract the coefficents and intercepts for the boundary line(s)

# Get the coefficents
coefficents = logisticReg.coef_

# Get the intercept
intercepts = logisticReg.intercept_

# Print coefficents and intercept
print('Coefficents: ', coefficents)
print('Intercepts: ', intercepts)

Sample datapoint:  [4.9 2.1 3.5 1.1]
The probability of setosa is:  [0.07]
The probability of versicolor is:  [0.91]
The probability of virginica is:  [0.01]

The score of test data: 100%

Coefficents:  [[-0.42685097  0.97283315 -2.44463796 -1.0318789 ]
 [ 0.51314447 -0.22362072 -0.21514806 -0.85146024]
 [-0.0862935  -0.74921243  2.65978602  1.88333914]]
Intercepts:  [  9.50133366   1.91164253 -11.4129762 ]


# Part 4: Support Vector Machine

In [27]:
# i. Use sklearn to train a Support Vector Classifier on the training set

# Train the training set on SVC use sklearn
svc = make_pipeline(StandardScaler(), SVC(gamma='auto', probability=True))
svc.fit(X_train, y_train)

# ii. For a sample datapoint, predict the probabilities for each possible class

# Create a sample datapoint
sample = np.array([4.9, 2.1, 3.5, 1.1])

# Predict the 
predict = svc.predict_proba([sample])

# Rounding to the nearest hundredth
sample_predict = np.round(predict, 2)

# Print the probabilities of each class upon the datapoint
print('Sample datapoint: ', sample)
print('The probability of setosa is: ' , sample_predict[:,0])
print('The probability of versicolor is: ' , sample_predict[:,1])
print('The probability of virginica is: ' , sample_predict[:,2])

# iii. Report on the score for the SVM, what does the score measure?

# Get the mean accuracy of iris dataset on SVM model
score = svc.score(X_test, y_test) * 100

# Print the mean accuracy
print('\nThe score of test data: %.f%%' % score)

Sample datapoint:  [4.9 2.1 3.5 1.1]
The probability of setosa is:  [0.02]
The probability of versicolor is:  [0.94]
The probability of virginica is:  [0.04]

The score of test data: 100%


# Part 5: Neural Network

In [37]:
# i. Use sklearn to train a Neural Network (MLP Classifier) on the training set

# Train the training set on MLP classifier
mlp = MLPClassifier(max_iter=600,
                    random_state=1).fit(X_train, y_train)

# ii. For a sample datapoint, predict the probabilities for each possible class

# Create a sample datapoint
sample = [[4.9, 2.1, 3.5, 1.1]]

# Predict the 
sample_predict = mlp.predict_proba(np.array(sample))

# Rounding to the nearest thousandth
sample_predict = np.round(sample_predict, 3)

# Print the probabilities of each class upon the datapoint
print('Sample datapoint: ', sample)
print('The probability of setosa is: ' , sample_predict[:,0])
print('The probability of versicolor is: ' , sample_predict[:,1])
print('The probability of virginica is: ' , sample_predict[:,2])


# iii. Report on the score for the Neural Network, what does the score measure?

# Get the mean accuracy of iris dataset on SVM model
score = mlp.score(X_test, y_test) * 100

# Print the mean accuracy
print('\nThe score of test data: %.f%%' % score)

# iv: Experiment with different options for the neural network, report on your best configuration (the highest score I was able to achieve was 0.8666)

mlp = MLPClassifier(max_iter=3000,
                    learning_rate_init = 0.002,
                    solver='adam', 
                    hidden_layer_sizes=(6,), 
                    random_state=1).fit(X_train, y_train)

# Get the mean accuracy of iris dataset on MLP Classifier model
score = mlp.score(X_test, y_test) * 100

# Print the mean accuracy
print('\nThe score of test data: %.f%%' % score)

Sample datapoint:  [[4.9, 2.1, 3.5, 1.1]]
The probability of setosa is:  [0.005]
The probability of versicolor is:  [0.982]
The probability of virginica is:  [0.014]

The score of test data: 100%

The score of test data: 93%


# Part 6: K-Nearest Neighbors

In [33]:
# i. Use sklearn to 'train' a k-Neighbors Classifier
# Note: KNN is a nonparametric model and technically doesn't require training
# fit will essentially load the data into the model see link below for more information
# https://stats.stackexchange.com/questions/349842/why-do-we-need-to-fit-a-k-nearest-neighbors-classifier

knc = KNeighborsClassifier(n_neighbors=3).fit(X_train, y_train)

# ii. For a sample datapoint, predict the probabilities for each possible class

# Create a sample datapoint
sample = np.array([[4.9, 2.1, 3.5, 1.1]])

# Predict the 
predict = knc.predict_proba(sample)

# Rounding to the nearest hundredth
sample_predict = np.round(predict, 2)

# Print the probabilities of each class upon the datapoint
print('Sample datapoint: ', sample)
print('The probability of setosa is: ' , sample_predict[:,0])
print('The probability of versicolor is: ' , sample_predict[:,1])
print('The probability of virginica is: ' , sample_predict[:,2])

# iii. Report on the score for kNN, what does the score measure?

# Get the mean accuracy of iris dataset on KNN classifier model
score = knc.score(X_test, y_test) * 100

# Print the mean accuracy
print('\nThe score of test data: %.f%%' % score)



Sample datapoint:  [[4.9 2.1 3.5 1.1]]
The probability of setosa is:  [0.]
The probability of versicolor is:  [1.]
The probability of virginica is:  [0.]

The score of test data: 100%


# Part 7: Conclusions and takeaways

In your own words describe the results of the notebook. Which model(s) performed the best on the dataset? Why do you think that is? Did anything surprise you about the exercise?